BookSale.Managerment.Ui/Areas/Admin/Controllers/AuthenticationController.cs
using BookSale.Managerment.Application.Abstracts;
using BookSale.Managerment.Domain.Abstract;
using BookSale.Managerment.Ui.Areas.Admin.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace BookSale.Managerment.Ui.Areas.Admin.Controllers
{
    [AllowAnonymous]
    public class AuthenticationController : BaseControl
    {
        private readonly IAuthenticationService _authenticationService;
        public AuthenticationController(IAuthenticationService authenticationService)
        {
            _authenticationService = authenticationService;         
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View(new LoginForm());
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginForm loginForm)
        {
            /*
                - Nếu modelstate hợp lệ thì tiến hành kiểm tra username và password
                - Nếu đúng thì lưu thông tin vào session và chuyển hướng đến trang chủ 
                - Ngược lại thì hiển thị lỗi ra view
            */
            if (ModelState.IsValid)
            {
                // Gọi đến service để check login
                var Response = await _authenticationService.CheckLogin(loginForm.Username, loginForm.Password, loginForm.RememberMe);

                if (!Response.Status)
                {
                    ViewBag.Error = Response.Message;
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                // Lấy ra các lỗi của ModelState
                var errors = ModelState.Values
                            .SelectMany(v => v.Errors)
                            .Select(e => e.ErrorMessage);

                ViewBag.errors = string.Join("<br/>", errors);
            }

            return View();
        }
        public async Task<IActionResult> Logout()
        {
            await _authenticationService.Logout();

            return Redirect(nameof(Login));
        }
    }
}

BookSale.Managerment.Ui/Areas/Admin/Controllers/BookController.cs
using BookSale.Managerment.Application.Abstracts;
using BookSale.Managerment.Application.DTOs;
using BookSale.Managerment.Ui.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace BookSale.Managerment.Ui.Areas.Admin.Controllers
{
    public class BookController : BaseControl
    {
        private readonly IBookService _bookService;
        private readonly IGenreService _genreService;
        private readonly ITagService _tagService;
        private readonly IUserService _userService;

        public BookController(IBookService bookService, IGenreService genreService, ITagService tagService, IUserService userService)
        {
            _bookService = bookService;
            _genreService = genreService;
            _tagService = tagService;
            _userService = userService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetBookList(RequestFilterModel filter)
        {
            if (filter == null || filter.Limit <= 0 || filter.Offset < 0)
            {
                return BadRequest(new { message = "Params khôn hợp lệ!" });
            }

            var result = await _bookService.GetBookList(filter);

            if (result.Status == false) return BadRequest(result);

            return Json(new TableViewModel<BookDTO>()
            {
                total = result.Total,
                Rows = result.Data?.ToList()
            });
        }
        public async Task<IActionResult> Save(int? id)
        {
            var genres = await _genreService.GetAll();
            var tags = await _tagService.GetAll();
            var authors = await _userService.GetAllAuthor();

            ViewBag.Genres = genres.Data ?? new List<GenreDTO>();
            ViewBag.Tags = tags.Data ?? new List<TagDTO>();
            ViewBag.Authors = authors.Data ?? new List<UserDto>();

            if(id is not null)
            {
                var result = await _bookService.GetBook(id.Value);

                if (result.Status == true && result.Data is not null) return View(result.Data);
                else return BadRequest(result);
            }
            return View(new BookDetailDTO());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(BookDetailDTO model)
        {
            if(!ModelState.IsValid)
            {
                return BadRequest();
            }

            var result = model.Id == 0 
                       ? await _bookService.Create(model)
                       : await _bookService.Update(model.Id, model);

            if(result.Status == false) return BadRequest(result);

            return View(result);
        }
    }
}

BookSale.Managerment.Ui/Areas/Admin/Controllers/GenreController.cs
using BookSale.Managerment.Application.Abstracts;
using BookSale.Managerment.Application.DTOs;
using BookSale.Managerment.Domain.constants;
using BookSale.Managerment.Ui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Threading.Tasks;

namespace BookSale.Managerment.Ui.Areas.Admin.Controllers
{
    public class GenreController : BaseControl
    {
        private readonly IGenreService _genreService;
        public GenreController(IGenreService genreService)
        {
            _genreService = genreService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> GenreList(RequestFilterModel filter)
        {
            if (filter == null || filter.Limit <= 0 || filter.Offset < 0)
            {
                return BadRequest(new { message = "Params khôn hợp lệ!" });
            }

            var result = await _genreService.GetGenreList(filter);

            if(result.Status == false) return BadRequest(result);

            return Json(new TableViewModel<GenreDTO>()
            {
                total = result.Total,
                Rows = result.Data?.ToList()
            });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(GenreDTO genreDTO)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(new ResponseModel(false, ResponseMessage.InvalidValue));
            }

            var result = genreDTO.Id == 0
                       ? await _genreService.Create(genreDTO)
                       : await _genreService.Update(genreDTO);

            if (result.Status) return Json(result);

            return BadRequest(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _genreService.Delete(id);

            if(result.Status)
                return Json(result);

            return BadRequest(result);
        }
    }
}

BookSale.Managerment.Ui/Areas/Admin/Controllers/TagController.cs
using BookSale.Managerment.Application.Abstracts;
using BookSale.Managerment.Application.DTOs;
using BookSale.Managerment.Domain.constants;
using BookSale.Managerment.Ui.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Threading.Tasks;

namespace BookSale.Managerment.Ui.Areas.Admin.Controllers
{
    public class TagController : BaseControl
    {
        private readonly ITagService _tagService;
        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> TagList(RequestFilterModel filter)
        {
            if (filter == null || filter.Limit <= 0 || filter.Offset < 0)
            {
                return BadRequest(new { message = "Params khôn hợp lệ!" });
            }

            var genres = await _tagService.GetTagList(filter);

            return Json(new TableViewModel<TagDTO>()
            {
                total = genres.Total,
                Rows = genres.Data?.ToList()
            });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Save(TagDTO genreDTO)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(new ResponseModel(false, ResponseMessage.InvalidValue));
            }

            var result = genreDTO.Id == 0
                       ? await _tagService.Create(genreDTO)
                       : await _tagService.Update(genreDTO);

            if (result.Status) return Json(result);

            return BadRequest(result);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            var result = await _tagService.Delete(id);

            if(result.Status)
                return Json(result);

            return BadRequest(result);
        }
    }
}

BookSale.Managerment.Ui/Areas/Admin/Views/Shared/_Footer.cshtml
<div class="d-sm-flex justify-content-center justify-content-sm-between">
  <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © bootstrapdash.com 2020</span>
  <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center"> Free <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span>
</div>

BookSale.Managerment.Ui/Areas/Admin/Views/Shared/_Header.cshtml
<nav class="navbar p-0 fixed-top d-flex flex-row">
  <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
    <a class="navbar-brand brand-logo-mini" href="index.html"><img src="~/assets/images/logo-mini.svg" alt="logo"></a>
  </div>
  <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
    <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
      <span class="mdi mdi-menu"></span>
    </button>
    <ul class="navbar-nav w-100">
      <li class="nav-item w-100">
        <form class="nav-link mt-2 mt-md-0 d-none d-lg-flex search">
          <input type="text" class="form-control" placeholder="Search products">
        </form>
      </li>
    </ul>
    <ul class="navbar-nav navbar-nav-right">
      <li class="nav-item dropdown d-none d-lg-block">
        @* <a class="nav-link btn btn-success create-new-button" id="createbuttonDropdown" data-toggle="dropdown"
          aria-expanded="false" href="#">+ Create New Project</a> *@
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
          aria-labelledby="createbuttonDropdown">
          <h6 class="p-3 mb-0">Projects</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-file-outline text-primary"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Software Development</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-web text-info"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">UI Development</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-layers text-danger"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1">Software Testing</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">See all projects</p>
        </div>
      </li>
      <li class="nav-item nav-settings d-none d-lg-block">
        <a class="nav-link" href="#">
          <i class="mdi mdi-view-grid"></i>
        </a>
      </li>
      <li class="nav-item dropdown border-left">
        <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-bell"></i>
          <span class="count bg-danger"></span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list"
          aria-labelledby="notificationDropdown">
          <h6 class="p-3 mb-0">Notifications</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-calendar text-success"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Event today</p>
              <p class="text-muted ellipsis mb-0"> Just a reminder that you have an event today </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-settings text-danger"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Settings</p>
              <p class="text-muted ellipsis mb-0"> Update dashboard </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-link-variant text-warning"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Launch Admin</p>
              <p class="text-muted ellipsis mb-0"> New admin wow! </p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">See all notifications</p>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
          <div class="navbar-profile">
            @if (@ViewBag.AvatarUrl != null)
            {
              <img class="img-xs rounded-circle" src="@ViewBag.AvatarUrl" alt="">
            }
            else
            {
              <img class="img-xs rounded-circle" src="~/assets/images/faces/face15.jpg" alt="">
            }
            <p class="mb-0 d-none d-sm-block navbar-profile-name">@User.Identity?.Name</p>
            <i class="mdi mdi-menu-down d-none d-sm-block"></i>
          </div>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
          <h6 class="p-3 mb-0">Hồ sơ</h6>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-settings text-success"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject mb-1">Cài đặt</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <form asp-area="Admin" asp-controller="Authentication" asp-action="Logout" method="post" id="logoutForm">
            <a class="dropdown-item preview-item" href="javascript:document.getElementById('logoutForm').submit()">
              <div class="preview-thumbnail">
                <div class="preview-icon bg-dark rounded-circle">
                  <i class="mdi mdi-logout text-danger"></i>
                </div>
              </div>
              <div class="preview-item-content">
                <p class="preview-subject mb-1">Đăng xuất</p>
              </div>
            </a>
          </form>
          <div class="dropdown-divider"></div>
          <p class="p-3 mb-0 text-center">Cài đặt nâng cao</p>
        </div>
      </li>
    </ul>
    <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button"
      data-toggle="offcanvas">
      <span class="mdi mdi-format-line-spacing"></span>
    </button>
  </div>
</nav>

BookSale.Managerment.Ui/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookSale.Managerment.Ui</title>


    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link rel="stylesheet" href="~/BookSale.Managerment.Ui.styles.css" asp-append-version="true" />
    <!-- plugins:css -->
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/assets/vendors/jvectormap/jquery-jvectormap.css">
    <link rel="stylesheet" href="~/assets/vendors/flag-icon-css/css/flag-icon.min.css">
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel-2/owl.carousel.min.css">
    <link rel="stylesheet" href="~/assets/vendors/owl-carousel-2/owl.theme.default.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- End layout styles -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="~/lib/bootstrap-table-master/dist/bootstrap-table.min.css">
    <!-- Layout styles -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <!-- toaster -->
    <link href="~/js/toaster/jquery.toast.min.css" rel="stylesheet" />
</head>

<body>
    <div class="container-scroller">
        @await Html.PartialAsync("_Sidebar")
        <div class="container-fluid page-body-wrapper">
            @await Html.PartialAsync("_Header")
            <div class="main-panel">
                <div class="content-wrapper">
                    @RenderBody()
                </div>
                <footer class="footer">
                    @await Html.PartialAsync("_Footer")
                </footer>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- container-scroller -->
    <!-- plugins:js -->
    <script src="~/assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="~/assets/vendors/chart.js/Chart.min.js"></script>
    <script src="~/assets/vendors/progressbar.js/progressbar.min.js"></script>
    <script src="~/assets/vendors/jvectormap/jquery-jvectormap.min.js"></script>
    <script src="~/assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js"></script>
    <script src="~/assets/vendors/owl-carousel-2/owl.carousel.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="~/assets/js/off-canvas.js"></script>
    <script src="~/assets/js/hoverable-collapse.js"></script>
    <script src="~/assets/js/misc.js"></script>
    <script src="~/assets/js/menu-active.js"></script>
    <script src="~/assets/js/settings.js"></script>
    <script src="~/assets/js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page -->
    <script src="~/assets/js/dashboard.js"></script>
    <!-- End custom js for this page -->
    <!-- toaster js -->
    <script src="~/js/toaster/jquery.toast.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="~/lib/bootstrap-table-master/dist/bootstrap-table.min.js"></script>
    <!-- Latest compiled and minified Locales -->
    <script src="~/lib/bootstrap-table-master/dist/locale/bootstrap-table-vi-VN.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="~/js/main.js"></script>

    <script src="~/js/bootstrapmodal.js"></script>

    
    <!-- validate -->
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

    <!-- moment.js -->
    <script src="~/lib/moment.min.js"></script>
    <script src="~/js/formatter.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

BookSale.Managerment.Ui/Areas/Admin/Views/Shared/_Sidebar.cshtml
<nav class="sidebar sidebar-offcanvas" id="sidebar">
  <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
    <a class="sidebar-brand brand-logo" href="index.html"><img src="~/assets/images/logo.svg" alt="logo"></a>
    <a class="sidebar-brand brand-logo-mini" href="index.html"><img src="~/assets/images/logo-mini.svg" alt="logo"></a>
  </div>
  <ul class="nav">
    <li class="nav-item profile">
      <div class="profile-desc">
        <div class="profile-pic">
          <div class="count-indicator">
            @if (@ViewBag.AvatarUrl != null)
            {
              <img class="img-xs rounded-circle" src="@ViewBag.AvatarUrl" alt="">
            }
            else
            {
              <img class="img-xs rounded-circle" src="~/assets/images/faces/face15.jpg" alt="">
            }
            <span class="count bg-success"></span>
          </div>
          <div class="profile-name">
            <h5 class="mb-0 font-weight-normal">@User.Identity?.Name</h5>
            <span></span>
          </div>
        </div>
        <a href="#" id="profile-dropdown" data-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
        <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
          <a href="#" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-settings text-primary"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1 text-small">Quản lý tài khoản</p>
            </div>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item preview-item">
            <div class="preview-thumbnail">
              <div class="preview-icon bg-dark rounded-circle">
                <i class="mdi mdi-onepassword  text-info"></i>
              </div>
            </div>
            <div class="preview-item-content">
              <p class="preview-subject ellipsis mb-1 text-small">Đổi mật khẩu</p>
            </div>
          </a>
        </div>
      </div>
    </li>
    <li class="nav-item nav-category">
      <span class="nav-link">Menu</span>
    </li>
    <li class="nav-item menu-items">
      <a class="nav-link" asp-action="Index" asp-controller="Home">
        <span class="menu-icon">
          <i class="mdi mdi-speedometer"></i>
        </span>
        <span class="menu-title">Tổng quan</span>
      </a>
    </li>
    <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#account-management" aria-expanded="false" aria-controls="account-management">
            <span class="menu-icon">
                <i class="mdi mdi-ticket-account"></i>
            </span>
            <span class="menu-title">Tài khoản</span>
            <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="account-management">
            <ul class="nav flex-column sub-menu">
                <li class="nav-item"> 
                    <a class="nav-link" asp-action="Save" asp-controller="Account">Tạo tài khoản</a>
                </li>
                <li class="nav-item"> 
                    <a class="nav-link" asp-action="AccountManagerment" asp-controller="Account">Quản lý tài khoản</a>
                </li>
            </ul>
      </div>
    </li>
    <li class="nav-item menu-items">
        <a class="nav-link" data-toggle="collapse" href="#book-management" aria-expanded="false" aria-controls="book-management">
            <span class="menu-icon">
                <i class="mdi mdi-ticket-account"></i>
            </span>
            <span class="menu-title">Sách</span>
            <i class="menu-arrow"></i>
        </a>
        <div class="collapse" id="book-management">
            <ul class="nav flex-column sub-menu">
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Book">Quản lý sách</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Genre">Quản lý thể loại</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-action="Index" asp-controller="Tag">Quản lý thẻ</a>
                </li>
            </ul>
        </div>
    </li>
  </ul>
</nav>